### ISSUE TITLE
1.21 Zombie Player does not drop their items.

### ISSUE THREAD

**Issue by bathala-a11y** [MC-Mods-Pete/ZombifiedPlayer#1] opened 2024-08-03 09:21 UTC
I tested this on the first release of your mod. The problem is that when the Zombie Player gets killed by ofc the player the items do not drop except for equipped items like armor and tools and weapons.

The intended purpose of this issue is that Zombie Player should be able to drop their inventory. Zombie Player would also drop rotten flesh in the process.

**Comment by MC-Mods-Pete** [comment] 2024-08-03 11:08
Thanks for reporting the issue. Can you please explain the problem a bit more.
Currently if "transfer the inventory" is enabled, the following should work:
- The item in the main and the off hand should be transferred
- the armor the player was wearing should be transferred
- the players inventory should be transferred
All of the above should be dropped, when the Zombified Player get killed
Is this the case for you?

The Zombified Player does not drop rotten flesh yet (will be added in the future)

**Comment by bathala-a11y** [comment] 2024-08-03 11:46
When a player is zombiefied, Meaning it does not drop inventory items nor equipped items. 

But when the zombified player is killed you dont get the loot back like inventory items, except for equipped items such as weapons, tools, or armor.

The exclusion of inventory items shouldnt happen and you get the loot back 100%.

**Comment by MC-Mods-Pete** [comment] 2024-08-03 19:47
Are you using other mods?
I can't reproduce your issue.
When I kill a Zombified Player it drops what I had in my inventory before I died.

**Comment by MC-Mods-Pete** [comment] 2024-08-03 19:56
Example:
My inventory before I was killed:
![grafik](https://github.com/user-attachments/assets/8d9323f4-720c-4193-ae4c-8b56ed972522)
It all got droped after I killed the Zombified Player (I already picked some items up before the screenshot):
![Bildschirmfoto vom 2024-08-03 21-55-12](https://github.com/user-attachments/assets/79fc7446-3c7e-4797-8aa6-9b43823b65b1)

**Comment by bathala-a11y** [comment] 2024-08-04 08:27
> Are you using other mods? I can't reproduce your issue. When I kill a Zombified Player it drops what I had in my inventory before I died.

is this a newer version?

**Comment by bathala-a11y** [comment] 2024-08-04 08:27
if so i have to test it out

**Comment by bathala-a11y** [comment] 2024-08-04 08:33
Ps. I tested the latest version but it's a bit laggy for some reason when dying. Killing the Zombified me and dropping all loot works. BTW when a Zombified Player is spawned i think it is better it do not despawn like they have name tags on them.

**Comment by MC-Mods-Pete** [comment] 2024-08-04 12:00
Ah is see the issue, the inventory does not get stored correctly when unloading and reloading the Zombified Player to the world.
(like also if you restart Minecraft)

I will release a hotfix, that disables Inventory Transfer until I have a fix.

**Comment by MC-Mods-Pete** [comment] 2024-08-05 21:50
can you please check release 0.9.3 if the issue is fixed :)

**Comment by makumaku1974** [comment] 2024-08-05 23:28
Will check it now

**Comment by makumaku1974** [comment] 2024-08-06 03:45
Will this merge with contagion soon? or just a separate? because I was thinking of merging it already instead of separate to prevent incompatibility with other mods. 

Also, with contagion on the other hand. Infection should now have a function dedicating with Zombified Player after death.

**Comment by MC-Mods-Pete** [comment] 2024-08-06 21:35
I will probably not merge the two mods anytime soon, because ZombifiedPlayer uses the new 1.21 network api and I want to keep Contagion compatible with 1.20.

But I'm working on a function so Contagion Infections cause a Zombified Player spawn :)

**Comment by MC-Mods-Pete** [comment] 2024-08-06 21:35
Another question: is this issue fixed now? :)

**Comment by makumaku1974** [comment] 2024-08-07 03:18
> Another question: is this issue fixed now? :)

this is fixed but after dying from the infection i dont turn into a zombie yet.

**Comment by MC-Mods-Pete** [comment] 2024-08-07 07:27
Then I will close this issue now. :)

> but after dying from the infection i dont turn into a zombie yet.

This will come in the next step :)
For now, as a workaround, you can disable the config option "Spawn zombified player only if player was killed by other Zombies". When disabled, a zombified player will spawn, no matter how the player dies.

**Closed as completed by MC-Mods-Pete** 2024-08-07 07:27 UTC
Labels: bug

**Comment by makumaku1974** [comment] 2024-08-07 10:24
> Then I will close this issue now. :)
> 
> > but after dying from the infection i dont turn into a zombie yet.
> 
> This will come in the next step :) For now, as a workaround, you can disable the config option "Spawn zombified player only if player was killed by other Zombies". When disabled, a zombified player will spawn, no matter how the player dies.

it's fine. I'll wait for the workaround to come soon.
